### ISSUE TITLE
Developer page has changed

### ISSUE THREAD

**Issue by miketech** [dJOS1475/Hubitat_Netatmo#1]
Currently during setup:

"you can get these details after creating a new application on https:\developer.netatmo.com"

The new domain is: https://dev.netatmo.com/

Maybe you can change it :) Thank you!

**Comment by dJOS1475** [comment]
no worries, I'll do that tomorrow.

**Comment by miketech** [comment]
Perfect thanks :)

**Comment by dJOS1475** [comment]
All sorted - v1.4 has been published.
